version: '3.8'

services:
  mintdb:
    container_name: mintdb
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-5tr0nger}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - postgres/:/var/lib/postgresql/data:rw
    networks:
      - app

  mint-app:
    env_file:
      - docker/.env
    container_name: mint-app
    build:
      context: docker/php
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/
    depends_on:
      - mintdb
    networks:
      - app

  mint-chat:
    container_name: chat
    build: docker/php/
    ports:
      - "8080:10000"
    restart: always
    volumes:
      - ./:/var/www
      - /etc/timezone:/etc/timezone
    networks:
      - app

  nginx_mint:
    container_name: nginx_mint
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/
      - ./docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - mint-app
      - mintdb
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  postgres:
