controllers:
    resource: ../../src/Controller/Frontend/
    type: annotation
    # Country codes: ISO 3166-1 (Alpha-2 code)
    prefix:
        global: '' # Глобальный регион (по-умолчанию)
api_controllers:
    resource: ../../src/Controller/Api/
    type: annotation
kernel:
    resource: ../../src/Kernel.php
    type: annotation
